### ISSUE TITLE
implement handler class

### ISSUE THREAD

**Issue by joemiller** [sensu-plugins/sensu-plugin-python#1]
implement Handler class. Goal is parity with the ruby lib.

we might be able to use ehazlett's work - https://github.com/ehazlett/sensu-py

**Comment by hubricode** [comment]
Sadly, ehazlett's work is incompatible with later sensu versions.
One year on and no progress with the python handler

https://github.com/sensu/sensu-plugin-python/issues/4

**Comment by barryorourke** [comment]
handler support has now been added into 0.4.0
