### ISSUE TITLE
Passing arguments

### ISSUE THREAD

**Issue by makaveli0129** [sensu-plugins/sensu-plugin-python#12]
Passing in any arguments into checks fails due to the the init of the Sensu Plugin class

Keep getting error: "unrecognized arguments"

Using program without the sensu plugin and it works fine.

**Comment by barryorourke** [comment]
Since this was submitted over a year ago, I suspect that it may not be an issue any more. If it is please let us know and we'll see if there is anything we can do to help.

Since this issue is so old, I'm going to close it in a week if no-one replies.

**Comment by makaveli0129** [comment]
yea with the new version of sensu you can define "stdin" attributes that are now fed directly into the check execution so i think this may not be needed anymore.

**Comment by barryorourke** [comment]
thanks for letting us know :)
