### ISSUE TITLE
In need of Maintainer(s)

### ISSUE THREAD

**Issue by mbbroberg** [sensu-plugins/sensu-plugin-python#14]
This repository is super helpful to those who use it. @zsprackett, @nstielau and @joemiller took great care of it for quite some time, but it looks now that they could use some help. 

I'd like to bring up the need to have a regular maintainer. Someone who is strong in python, knows Sensu and is willing to join a growing number of maintainers across the Sensu projects (active members include @eheydrick @majormoses @luisdavim @sstarcher @mattyjones). 

If you're interested, please comment on this issue. If you're a user of this repo, please give a 👍 to let us know you're using it and this is important to you.

**Comment by majormoses** [comment]
I am certainly more than happy to maintain this, I have not done much python in a few years but look forward to picking that back up.

I would like to pose the question of if this currently is helpful enough to migrate to the sensu-plugins org or if we should start from scratch to untie our hands from any decisions that were previously made. I have not looked into the code yet so I do not yet have an opinion other than whatever the go forward path needs to live in sensu-plugins org.

**Comment by mbbroberg** [comment]
That's a great discussion point @majormoses. I will also be reaching out to people more focused on Python that may have a vested interest in improving what is here. I would like either outcome, though I prefer if someone who has more time focused on Python+Sensu dives in.

**Comment by barryorourke** [comment]
As discused on slack I'd quite happily maintain this project or start an alternative from scratch that integrates sensu with python in a sensible manner.

All of the in-house checks we write at work are done in python and it would be good to have a solid alternative to the sensu_plugin gem to make life easier for python developers.

**Comment by luisdavim** [comment]
I'm very happy to learn that this exists I've mentioned before that we do need something like sensu-plugin for python. I didn't look at the code yet but for sure I can give an hand when needed.

**Comment by zsprackett** [comment]
I’m happy to get anyone more active access.

**Comment by barryorourke** [comment]
This can be closed now that @luisdavim and I are set up as maintainers.
