### ISSUE TITLE
PyPI access and housekeeping

### ISSUE THREAD

**Issue by barryorourke** [sensu-plugins/sensu-plugin-python#15]
The issue will be used to track all of the housekeeping work required to allow the new maintainers of this repo access to PyPI, so that we are able to make releases.

- [x] @barryorourke added to the Package Index Owners list
- [x] @absolutejam, @majormoses added to the Package Index Owners list
- [x] sensu_plugins account created on PyPI
- [x] sensu_plugins account added to the Package Index Owners list
- [x] demote everyone except sensu_plugins to maintainer.

**Comment by barryorourke** [comment]
@zsprackett could you add me to the owners list of sensu_plugin on PyPI please? My username is barryorourke.

**Comment by zsprackett** [comment]
@barryorourke added you.

**Comment by barryorourke** [comment]
@zsprackett Thanks, I noticed that you added me as a maintainer rather than an owner and was wondering if you would be willing to hand over ownership to the sensu plugins community? From my understanding this is how the majority of gems that the community maintain are managed. @majormoses Is that right?

**Comment by zsprackett** [comment]
Yes, I'm willing to do that.

**Comment by majormoses** [comment]
Yes the community takes ownership and will share maintainer/ownership with those that previously maintained it unless they no longer want to.

**Comment by barryorourke** [comment]
@zsprackett Could you add the Sensu_Plugins user on PyPI to the owner list please?

**Comment by barryorourke** [comment]
@zsprackett I was wondering if you were still happy with handing over ownership of the module to the "Sensu_Plugins" user on PyPI?

**Comment by barryorourke** [comment]
@zsprackett thanks for taking care of this for us.

@luisdavim what's your PyPI username?

**Comment by barryorourke** [comment]
@absolutejam do you have a pypi account? If not could you set one up so that I can add you as a maintainer.

**Comment by absolutejam** [comment]
Just signed up with 'absolutejam' :+1:
