### ISSUE TITLE
Python version support

### ISSUE THREAD

**Issue by barryorourke** [sensu-plugins/sensu-plugin-python#17]
I'd like to change the version of python supported by the module from the current;

2.7, 3.3, 3.4

to the more modern;

2.7, 3.4, 3.6

and also propose that we follow a similar support model as the ruby module, which is to support all non-EOL versions.

Looking for SGTM's from at least two of the following @luisdavim, @majormoses, @mbbroberg & @eheydrick, comments from others are very welcome :)

**Comment by luisdavim** [comment]
SGTM :)

**Comment by eheydrick** [comment]
SGTM. 👍

**Comment by majormoses** [comment]
SGTM
