### ISSUE TITLE
Document and refactor/simplify existing codebase

### ISSUE THREAD

**Issue by absolutejam** [sensu-plugins/sensu-plugin-python#42]
Work on adding missing docstrings and general documentation to existing codebase, and explain some of the design choices (Eg. use of exit hook).

This will pave the way for easier refactoring for testing and generally make the project more usable as a starting point, and for debugging.

**Comment by barryorourke** [comment]
I now understand the majority of what is going on in the codebase and will simplify as I add new features over the next few weeks.
