### ISSUE TITLE
License information in classifiers

### ISSUE THREAD

**Issue by georgyo** [sensu-plugins/sensu-plugin-python#68]
This is a pretty mundane issue. You declare the license as `LICENSE.txt` in `setup.py`. This makes this code slightly harder to import in organizations that checks licenses.

If you look at meta information on pypi.org for your package, you will see that your license is just LICENSE.txt: https://pypi.org/project/sensu_plugin/

```
license='LICENSE.txt',
```
should become
```
classifiers=[
        'Programming Language :: Python :: 2.7',
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
],
```

Even more mundane. `LICENSE.txt` should get renamed to just `LICENSE`

More about info about these changes can be found here: https://packaging.python.org/tutorials/packaging-projects

**Comment by barryorourke** [comment]
That's 0.8.0 released with your suggested changes implemented, hopefully that will resolve this issue.
