### ISSUE TITLE
Graphite plugin does not allow passing objects to unknown()

### ISSUE THREAD

**Issue by xiongchiamiov** [sensu-plugins/sensu-plugin-python#69]
When using `SensuPluginMetricGraphite`, doing something like
```
try:
    some_code()
except Exception as e:
    self.unknown(e)
```
does not work, giving an IndexError.

[The code of this class](https://github.com/sensu-plugins/sensu-plugin-python/blob/master/sensu_plugin/metric.py#L27-L37) isn't terribly obvious and isn't documented, so it's hard to ascertain what the intended behavior and API are.  But I'm guessing that this use case is supposed to work, based on the second if statement:

```
        elif isinstance(args[0], Exception) or args[1] is None:
            print(args[0])
```

However, it never will when called via `ok()`, `unknown()`, etc.  This is because [the base class forwards its arguments as a tuple](https://github.com/sensu-plugins/sensu-plugin-python/blob/master/sensu_plugin/plugin.py#L66), so when `SensuPluginMetricGraphite` gets to it, you'll have a tuple of whatever the original arguments are (for instance, a one-element tuple of an Exception).

Changing `self.output(args)` to `self.output(*args)` fixes this, but will probably break other things; I think the root of the problem is that some of [the subclasses](https://github.com/sensu-plugins/sensu-plugin-python/blob/master/sensu_plugin/metric.py) use `def output(self, args)`, while others use `def output(self, *args)`, making it hard to reason about how data should be passed into all of them from one place.

**Comment by barryorourke** [comment]
I've been taking a look at the metrics classes with the intention of adding support for a Generic class similar to the one in the Ruby gem and have came to the same conclusion, I'm going to spend some time trying to figure out why the original author made these decisions and see if it can be simplifed and documented.

**Comment by barryorourke** [comment]
I've merged a fix for this into master, will be doing a release later in the week.
