### ISSUE TITLE
Go Python 3!

### ISSUE THREAD

**Issue by guedressel** [sensu-plugins/sensu-plugin-python#8]
Would be nice to work with sensu_plugin on python 3.

**Comment by dbrgn** [comment]
The current `master` version works with Python3, but the PyPI version is outdated.

**Comment by rchacon1** [comment]
Can you tag release 0.2.0 in github? Since the version on PYPI is outdated, I forked this repo just so I can tag it. That way I know what version I'm getting when I pip install from github.

**Comment by majormoses** [comment]
@rchacon1 sorry for the long silence the community is starting to take ownership and once we sort out some things we will follow the same cadence as it's ruby counterpart and release every functional change. See #15 #14 for more details.

**Comment by majormoses** [comment]
0.2.0 has been released. I am closing this out.
